require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/my_transactions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MyTransaction. As you add validations to MyTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MyTransaction.create! valid_attributes
      get my_transactions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      my_transaction = MyTransaction.create! valid_attributes
      get my_transaction_url(my_transaction)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_my_transaction_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      my_transaction = MyTransaction.create! valid_attributes
      get edit_my_transaction_url(my_transaction)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MyTransaction" do
        expect {
          post my_transactions_url, params: { my_transaction: valid_attributes }
        }.to change(MyTransaction, :count).by(1)
      end

      it "redirects to the created my_transaction" do
        post my_transactions_url, params: { my_transaction: valid_attributes }
        expect(response).to redirect_to(my_transaction_url(MyTransaction.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MyTransaction" do
        expect {
          post my_transactions_url, params: { my_transaction: invalid_attributes }
        }.to change(MyTransaction, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post my_transactions_url, params: { my_transaction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested my_transaction" do
        my_transaction = MyTransaction.create! valid_attributes
        patch my_transaction_url(my_transaction), params: { my_transaction: new_attributes }
        my_transaction.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the my_transaction" do
        my_transaction = MyTransaction.create! valid_attributes
        patch my_transaction_url(my_transaction), params: { my_transaction: new_attributes }
        my_transaction.reload
        expect(response).to redirect_to(my_transaction_url(my_transaction))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        my_transaction = MyTransaction.create! valid_attributes
        patch my_transaction_url(my_transaction), params: { my_transaction: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested my_transaction" do
      my_transaction = MyTransaction.create! valid_attributes
      expect {
        delete my_transaction_url(my_transaction)
      }.to change(MyTransaction, :count).by(-1)
    end

    it "redirects to the my_transactions list" do
      my_transaction = MyTransaction.create! valid_attributes
      delete my_transaction_url(my_transaction)
      expect(response).to redirect_to(my_transactions_url)
    end
  end
end
